In [65]:
import pandas as pd
import numpy as np
from keras.utils.np_utils import to_categorical

# 用pandas查看数据

In [66]:
pd_data = pd.read_csv(r"tsp_data/tsp_5/tsp5_train.txt",sep=" ")
pd_data

0.597640340831  0.811472963882  0.378392540696  0.188165799059  \
0             0.616749        0.862917        0.646589        0.211572   
1             0.379030        0.890446        0.322734        0.282492   
2             0.533508        0.330255        0.243859        0.096770   
3             0.853261        0.868294        0.247799        0.914311   
4             0.194521        0.250352        0.444690        0.294712   
...                ...             ...             ...             ...   
999994        0.537250        0.288174        0.434028        0.251542   
999995        0.233550        0.175775        0.095195        0.483445   
999996        0.139867        0.662865        0.598948        0.817055   
999997        0.559944        0.310630        0.767035        0.426365   
999998        0.734121        0.612339        0.434179        0.710144   

        0.442849630371  0.291815169363  0.363774192611  0.596244647907  \
0             0.669940        0.475992        0.339817        0.391328   
1             0.823656        0.667440        0.585095        0.990539   
2             0.495619        0.133440        0.864500        0.021500   
3             0.953246        0.291881        0.310663        0.805400   
4             0.487987        0.062408        0.681582        0.252301   
...                ...             ...             ...             ...   
999994        0.457031        0.065902        0.633687        0.070079   
999995        0.117582        0.459116        0.089660        0.497597   
999996        0.817873        0.676763        0.560807        0.016862   
999997        0.195640        0.354084        0.386345        0.048603   
999998        0.775295        0.843436        0.333334        0.450270   

        0.955211930984  0.947031856076  output  1  4  2  3  5  1.1  \
0             0.470565        0.253927  output  1  3  2  5  4    1   
1             0.402747        0.185903  output  1  2  5  3  4    1   
2             0.959150        0.210121  output  1  2  3  4  5    1   
3             0.503846        0.056197  output  1  2  4  5  3    1   
4             0.270056        0.308489  output  1  5  2  4  3    1   
...                ...             ...     ... .. .. .. .. ..  ...   
999994        0.197201        0.562749  output  1  5  2  3  4    1   
999995        0.002477        0.016063  output  1  3  2  4  5    1   
999996        0.950601        0.495861  output  1  2  3  5  4    1   
999997        0.299394        0.073220  output  1  4  5  3  2    1   
999998        0.942541        0.080612  output  1  3  2  4  5    1   

        Unnamed: 17  
0               NaN  
1               NaN  
2               NaN  
3               NaN  
4               NaN  
...             ...  
999994          NaN  
999995          NaN  
999996          NaN  
999997          NaN  
999998          NaN  

[999999 rows x 18 columns]

加载 x  
\[samples, time_steps, feature]  
\[样本数，城市数目，2]  

In [67]:
x_train = np.loadtxt(r"tsp_data/tsp_5/tsp5_train.txt",usecols=range(0,10))
x_test = np.loadtxt(r"tsp_data/tsp_5/tsp5_test.txt",usecols=range(0,10))

In [68]:
x_train.shape

(1000000, 10)

In [69]:
x_test.shape

(10000, 10)

In [70]:
x_train = x_train.reshape((1000000,5,2))
x_test = x_test.reshape((10000,5,2))
x_test

array([[[0.02939179, 0.00964774],
        [0.36771967, 0.01061911],
        [0.6941572 , 0.30306739],
        [0.72476562, 0.67138209],
        [0.27330556, 0.95539236]],

       [[0.52844706, 0.72382035],
        [0.76059043, 0.57296281],
        [0.10697758, 0.16078577],
        [0.3466064 , 0.46512958],
        [0.69620479, 0.37592563]],

       [[0.94699081, 0.03307697],
        [0.9062517 , 0.33310361],
        [0.86770989, 0.05046198],
        [0.2587944 , 0.88542052],
        [0.06609635, 0.10331539]],

       ...,

       [[0.62862836, 0.92268072],
        [0.44427856, 0.57644376],
        [0.61574079, 0.13294286],
        [0.11248611, 0.17990384],
        [0.76538208, 0.87967792]],

       [[0.09972703, 0.12856938],
        [0.06715542, 0.9663578 ],
        [0.49565377, 0.23600432],
        [0.00538825, 0.79734351],
        [0.22504104, 0.71391457]],

       [[0.05190828, 0.31293221],
        [0.03883916, 0.83874733],
        [0.31831644, 0.83584855],
        [0.72596161, 0.39

In [71]:
np.save(r"tsp_data/tsp_5/tsp5_train_x.npy",x_train)
np.save(r"tsp_data/tsp_5/tsp5_test_x.npy",x_test)

加载 y  
\[samples, time_steps, prob]  
\[样本数，城市数目，每个城市对应的概率]  


In [77]:
y_train = np.loadtxt(r"tsp_data/tsp_5/tsp5_train.txt",dtype=str,usecols=range(11,16))
y_train = y_train.astype(float)
y_test = np.loadtxt(r"tsp_data/tsp_5/tsp5_test.txt",dtype=str,usecols=range(11,16))
y_test = y_test.astype(float)
y_test

array([[1., 2., 3., 4., 5.],
       [1., 2., 5., 3., 4.],
       [1., 3., 5., 4., 2.],
       ...,
       [1., 2., 4., 3., 5.],
       [1., 3., 5., 2., 4.],
       [1., 2., 3., 4., 5.]])

In [78]:
y_train = y_train-1
y_test = y_test-1
y_test

array([[0., 1., 2., 3., 4.],
       [0., 1., 4., 2., 3.],
       [0., 2., 4., 3., 1.],
       ...,
       [0., 1., 3., 2., 4.],
       [0., 2., 4., 1., 3.],
       [0., 1., 2., 3., 4.]])

In [79]:
yy_train = []
for per in y_train:
    yy_train.append(to_categorical(per,num_classes=5))
yy_train = np.asarray(yy_train)
yy_train

array([[[1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]],

       ...,

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]], dtype=float32)

In [80]:
yy_test = []
for per in y_train:
    yy_test.append(to_categorical(per,num_classes=5))
yy_test = np.asarray(yy_test)
yy_test

array([[[1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]],

       ...,

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]], dtype=float32)

In [81]:
np.save(r"tsp_data/tsp_5/tsp5_train_y.npy",yy_train)
np.save(r"tsp_data/tsp_5/tsp5_test_y.npy",yy_test)