In [42]:
import pandas as pd
import numpy as np
from keras.utils.np_utils import to_categorical

# 用pandas查看数据

In [ ]:
pd_data = pd.read_csv(r"tsp_data/tsp_5/tsp5_train.txt",sep=" ")
pd_data

加载 x
\[samples, time_steps, feature]
\[样本数，城市数目，2]

In [ ]:
x = np.loadtxt(r"tsp_data/tsp_5/tsp5_train.txt",usecols=range(0,10))
x

In [45]:
x = x.reshape((1000000,5,2))
x

array([[[0.59764034, 0.81147296],
        [0.37839254, 0.1881658 ],
        [0.44284963, 0.29181517],
        [0.36377419, 0.59624465],
        [0.95521193, 0.94703186]],

       [[0.61674873, 0.86291727],
        [0.64658903, 0.21157218],
        [0.66993989, 0.47599156],
        [0.33981673, 0.39132813],
        [0.47056451, 0.25392741]],

       [[0.37902951, 0.89044637],
        [0.3227339 , 0.28249158],
        [0.82365648, 0.66743955],
        [0.58509472, 0.9905391 ],
        [0.40274668, 0.18590323]],

       ...,

       [[0.13986744, 0.66286485],
        [0.59894779, 0.81705535],
        [0.81787341, 0.67676271],
        [0.56080681, 0.01686202],
        [0.95060133, 0.4958608 ]],

       [[0.55994436, 0.31062955],
        [0.76703542, 0.42636486],
        [0.19564011, 0.35408403],
        [0.38634472, 0.04860255],
        [0.29939371, 0.07321974]],

       [[0.73412132, 0.61233866],
        [0.43417872, 0.71014415],
        [0.77529509, 0.84343557],
        [0.33333422, 0.45

In [46]:
np.save(r"tsp_data/tsp_5/tsp5_train_x.npy",x)

加载 y
\[samples, time_steps, prob]
\[样本数，城市数目，每个城市对应的概率]


In [ ]:
y = np.loadtxt(r"tsp_data/tsp_5/tsp5_train.txt",dtype=str,usecols=range(11,16))
y = y.astype(float)
y

In [48]:
y = y-1
y

array([[0., 3., 1., 2., 4.],
       [0., 2., 1., 4., 3.],
       [0., 1., 4., 2., 3.],
       ...,
       [0., 1., 2., 4., 3.],
       [0., 3., 4., 2., 1.],
       [0., 2., 1., 3., 4.]])

In [51]:
yy = []
for per in y:
    yy.append(to_categorical(per,num_classes=5))
yy = np.asarray(yy)
yy

array([[[1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]],

       ...,

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]],

       [[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]], dtype=float32)

In [50]:
np.save(r"tsp_data/tsp_5/tsp5_train_y.npy",yy)